import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.dates as mdates
from datetime import timedelta

def plot_production_schedule(df):
    # 🗓️ Filter the dataframe to only include calendar weeks 24–29 (from June 9 to July 18, 2025)
    df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)
    df = df[(df['Date'] >= '2025-06-09') & (df['Date'] <= '2025-07-18')]

    # 🔁 Set up the full range of days within the 6-week window
    start_date = pd.to_datetime('2025-06-09')
    end_date = pd.to_datetime('2025-07-18')
    all_dates = pd.date_range(start=start_date, end=end_date, freq='D')

    # ⚙️ Get unique machine names and visible materials from the filtered data
    machines = sorted(df['Machine'].dropna().unique())
    visible_df = df[(df['Date'] >= start_date) & (df['Date'] <= end_date)]
    materials = visible_df['Material'].dropna().unique()

    # 🎨 Assign a color to each material (cycling through the tab20 palette)
    palette = plt.cm.tab20.colors
    color_map = {mat: palette[i % len(palette)] for i, mat in enumerate(materials)}
    color_map[None] = 'black'  # Use black for standstill/setup slots

    # 🖼️ Create the plot
    fig, ax = plt.subplots(figsize=(14, 6))
    ax2 = ax.secondary_xaxis(-0.01)  # Add a secondary X-axis below for calendar weeks

    # 📊 Plot daily horizontal bars for each machine
    for i, machine in enumerate(machines):
        machine_df = df[df['Machine'] == machine].set_index('Date')
        y_pos = len(machines) - 1 - i  # Reverse Y to have machine 1 at the top
        for day in all_dates:
            mat = machine_df['Material'].get(day, None)
            if pd.isna(mat):
                mat = None
            color = color_map.get(mat, 'black')
            ax.barh(y_pos, 1, left=day, color=color, edgecolor='white')  # Bar length = 1 day

    # 🧭 Set Y-axis to show machine names
    ax.set_yticks(range(len(machines)))
    ax.set_yticklabels(machines)
    ax.set_ylabel("Machine", fontsize=14, fontweight='bold')

    # 📆 Format the X-axis with daily ticks and day names
    ax.set_xlim(start_date, end_date + timedelta(days=1))
    ax.set_xticks(all_dates)
    ax.xaxis.set_major_locator(mdates.DayLocator())
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%a'))  # Show day names (Mon, Tue, ...)
    plt.setp(ax.get_xticklabels(), rotation=0, ha='center', fontsize=8)

    # ➖ Add vertical lines to mark the beginning of each calendar week
    week_starts = pd.date_range(start=start_date, end=end_date, freq='W-MON')
    for i, date in enumerate(week_starts):
        ax.axvline(date, color='black', linestyle='--', linewidth=1.5)
        if i % 2 == 0:
            # 🖌️ Light shading for alternating weeks (for readability)
            ax.axvspan(date, date + timedelta(days=7), color='black', alpha=0.07)

    # ⬇️ Bottom axis shows calendar week numbers
    week_labels = [f"KW {d.isocalendar().week}\n{d.isocalendar().year}" for d in week_starts]
    week_midpoints = [d + timedelta(days=3) for d in week_starts]  # Place label in the middle of the week
    ax2.set_xlim(start_date, end_date + timedelta(days=1))
    ax2.set_xticks(week_midpoints)
    ax2.set_xticklabels(week_labels, fontsize=9, fontweight='bold')
    ax2.spines['bottom'].set_visible(False)
    ax2.tick_params(axis='x', which='major', pad=15, length=0)
    ax2.set_xlabel("Calendar Week", fontsize=14, fontweight='bold')

    # 🏷️ Add title and legend
    ax.set_title("6-Week Production Schedule (A3C Model)", fontsize=14, fontweight='bold')
    legend_patches = [mpatches.Patch(color=color, label=mat if mat else 'Standstill/Setup')
                      for mat, color in color_map.items()]
    ax.legend(handles=legend_patches, bbox_to_anchor=(1.01, 1), loc='upper left')

    # 🎯 Final plot settings
    plt.tight_layout()
    plt.grid(axis='x', linestyle='--', alpha=0.2)
    plt.show()


# ✅ Load the daily production schedule generated by the A3C model
df = pd.read_excel("production_schedule_6_weeks_daily.xlsx")

# ✅ Only plot calendar weeks 24–29
plot_production_schedule(df)

